CREATE TABLE IF NOT EXISTS actu
(
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    contenu VARCHAR(1024),
    Thematique_ID INT FOREIGN KEY REFERENCES thematique,
    date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS groupe
(
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    nom VARCHAR(255),
);

CREATE TABLE IF NOT EXISTS groupe_actu
(
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    groupe_ID INT FOREIGN KEY REFERENCES groupe,
    actu_ID INT FOREIGN KEY REFERENCES actu
);

CREATE TABLE IF NOT EXISTS thematique
(
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    valeur VARCHAR(255)
);
