CREATE TABLE IF NOT EXISTS thematique
(
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    valeur VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS actu
(
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    contenu VARCHAR(1024),
    Thematique_ID INT,
    date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (Thematique_ID) REFERENCES thematique(id)
);

CREATE TABLE IF NOT EXISTS groupe
(
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    nom VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS groupe_actu
(
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    groupe_ID INT,
    actu_ID INT,
    FOREIGN KEY (groupe_ID) REFERENCES groupe(id),
    FOREIGN KEY (actu_ID) REFERENCES actu(id)
);

